# Generated by Django 5.2 on 2025-05-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabaty_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
